services:
  - type: web
    name: fjc-pizza-app
    runtime: python
    runtimeVersion: "3.13"
    # run from repo root so requirements.txt is found
    # removed rootDir to use repo root
    buildCommand: |
      pip install -r requirements.txt
      cd kay-jenny/kay-jenny && python sales_inventory_system/manage.py migrate
      cd kay-jenny/kay-jenny && python sales_inventory_system/manage.py collectstatic --no-input
    startCommand: |
      cd kay-jenny/kay-jenny && gunicorn sales_inventory_system.sales_inventory.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: PYTHONUNBUFFERED
        value: "1"
    autoDeploy: true
    healthCheckPath: /admin/
    plan: free
